name: AlphaBridge
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bottleneck=1.3.7
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - pandas=2.2.2
  - pip=24.2
  - python=3.9.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - biopython==1.84
    - contourpy==1.3.0
    - cycler==0.12.1
    - fonttools==4.54.1
    - igraph==0.11.8
    - importlib-resources==6.4.5
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - matplotlib==3.9.2
    - networkx==3.2.1
    - packaging==24.1
    - pdbecif==1.5
    - pillow==11.0.0
    - pycirclize==1.7.1
    - pyparsing==3.2.0
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - zipp==3.20.2
